name: E2E Cypress Tests
on: workflow_dispatch
jobs:
    cypress-run:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Run Cypress Tests
              uses: cypress-io/github-action@v6
              with:
                browser: chrome

            - name: Upload Cypress Test Screenshots
              uses: actions/upload-artifact@v4
              if: failure()
              with:
                name: cypress-screenshots
                path: cypress/screenshots